language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - VISIONENGINE_HOME=$(pwd); echo VISIONENGINE_HOME = $VISIONENGINE_HOME > .env
install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - conda activate visionengine
  - python setup.py install
script:
  - python VisionEngine/tests/variational_layer_test.py