name: visionengine

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.1
  - cudnn=7.6
  - nccl=2.5
  - cupti=10.1
  - pip=20.0
  - python=3.7
  - tensorflow-gpu=2.2
  - tensorflow-probability
  - numpy=1.18.1
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - Pillow=7.0.0
  - openTSNE=0.3.12
  - numba=0.46.0
  - notebook=6.0.3
  - matplotlib=3.1.3
  - python-dotenv=0.14.0
  - tqdm=4.48.2 
  - pip:
    - dotmap==1.3.13

